#!/usr/bin/env sh
. "$(dirname "$0")/_/husky.sh"

[ -n "$CI" ] && exit 0

changedFiles="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

hasChanged() {
	echo "$changedFiles" | grep -q "$1"
}

if hasChanged 'pnpm-lock.yaml'; then
	pnpm install
fi
